package lu.wealins.lissia_services.db.entity;

// default package
// Generated Nov 25, 2016 3:32:04 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bills generated by hbm2java
 */
@Entity
@Table(name = "BILLS", catalog = "Lissia_QA5")
public class Bills implements java.io.Serializable {

	private long bilNo;
	private String policy;
	private String collectionReference;
	private Date date0;
	private BigDecimal amount;
	private String currency;
	private Integer method;
	private Integer subMethod;
	private Integer rejection;
	private String createdProcess;
	private String modifyProcess;
	private int status;
	private String createdBy;
	private Date createdDate;
	private Date createdTime;
	private String modifyBy;
	private Date modifyDate;
	private Date modifyTime;
	private Long fkBillingRunsbirId;
	private String fkPoliciespolId;

	public Bills() {
	}

	public Bills(long bilNo, int status) {
		this.bilNo = bilNo;
		this.status = status;
	}

	public Bills(long bilNo, String policy, String collectionReference,
			Date date0, BigDecimal amount, String currency, Integer method,
			Integer subMethod, Integer rejection, String createdProcess,
			String modifyProcess, int status, String createdBy,
			Date createdDate, Date createdTime, String modifyBy,
			Date modifyDate, Date modifyTime, Long fkBillingRunsbirId,
			String fkPoliciespolId) {
		this.bilNo = bilNo;
		this.policy = policy;
		this.collectionReference = collectionReference;
		this.date0 = date0;
		this.amount = amount;
		this.currency = currency;
		this.method = method;
		this.subMethod = subMethod;
		this.rejection = rejection;
		this.createdProcess = createdProcess;
		this.modifyProcess = modifyProcess;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.createdTime = createdTime;
		this.modifyBy = modifyBy;
		this.modifyDate = modifyDate;
		this.modifyTime = modifyTime;
		this.fkBillingRunsbirId = fkBillingRunsbirId;
		this.fkPoliciespolId = fkPoliciespolId;
	}

	@Id
	@Column(name = "BIL_NO", unique = true, nullable = false, precision = 12, scale = 0)
	public long getBilNo() {
		return this.bilNo;
	}

	public void setBilNo(long bilNo) {
		this.bilNo = bilNo;
	}

	@Column(name = "POLICY", length = 14)
	public String getPolicy() {
		return this.policy;
	}

	public void setPolicy(String policy) {
		this.policy = policy;
	}

	@Column(name = "COLLECTION_REFERENCE", length = 16)
	public String getCollectionReference() {
		return this.collectionReference;
	}

	public void setCollectionReference(String collectionReference) {
		this.collectionReference = collectionReference;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE0", length = 23)
	public Date getDate0() {
		return this.date0;
	}

	public void setDate0(Date date0) {
		this.date0 = date0;
	}

	@Column(name = "AMOUNT", precision = 15)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "CURRENCY", length = 5)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "METHOD")
	public Integer getMethod() {
		return this.method;
	}

	public void setMethod(Integer method) {
		this.method = method;
	}

	@Column(name = "SUB_METHOD")
	public Integer getSubMethod() {
		return this.subMethod;
	}

	public void setSubMethod(Integer subMethod) {
		this.subMethod = subMethod;
	}

	@Column(name = "REJECTION")
	public Integer getRejection() {
		return this.rejection;
	}

	public void setRejection(Integer rejection) {
		this.rejection = rejection;
	}

	@Column(name = "CREATED_PROCESS", length = 12)
	public String getCreatedProcess() {
		return this.createdProcess;
	}

	public void setCreatedProcess(String createdProcess) {
		this.createdProcess = createdProcess;
	}

	@Column(name = "MODIFY_PROCESS", length = 12)
	public String getModifyProcess() {
		return this.modifyProcess;
	}

	public void setModifyProcess(String modifyProcess) {
		this.modifyProcess = modifyProcess;
	}

	@Column(name = "STATUS", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "CREATED_BY", length = 5)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TIME", length = 23)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "MODIFY_BY", length = 5)
	public String getModifyBy() {
		return this.modifyBy;
	}

	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 23)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 23)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "FK_BILLING_RUNSBIR_ID", precision = 12, scale = 0)
	public Long getFkBillingRunsbirId() {
		return this.fkBillingRunsbirId;
	}

	public void setFkBillingRunsbirId(Long fkBillingRunsbirId) {
		this.fkBillingRunsbirId = fkBillingRunsbirId;
	}

	@Column(name = "FK_POLICIESPOL_ID", length = 14)
	public String getFkPoliciespolId() {
		return this.fkPoliciespolId;
	}

	public void setFkPoliciespolId(String fkPoliciespolId) {
		this.fkPoliciespolId = fkPoliciespolId;
	}

}
